version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    container_name: test
    ports:
      - '8090:80'
#      python db_utils.py;
    command: bash -c "python scripts/auto_parser_and_db_fill.py; uvicorn main:app --host 0.0.0.0 --port 80"
    env_file:
      - .env
    depends_on:
      - db


